sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

matrix:
  include:
    - php: 5.6
      env: CS_CHECK=1
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4

before_script: composer install --ignore-platform-reqs

script:
  - composer test
  - |
    if [[ "$CS_CHECK" == "1" ]] ; then
      composer cs-check
    fi
